apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "master_address.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "master_address.name" . }}
    helm.sh/chart: {{ include "master_address.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "master_address.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "master_address.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /master_address
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /master_address
          #     port: http
          volumeMounts:
          - name: {{ include "master_address.fullname" . }}
            mountPath: "/srv/sites/master_address/data/site_config.inc"
            subPath: "site_config.inc"
          - name: {{ include "master_address.fullname" . }}
            mountPath: "/etc/apache2/sites-available/000-default.conf"
            subPath: "000-default.conf"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: {{ include "master_address.fullname" . }}
        configMap:
          name: {{ include "master_address.fullname" . }}