---
- hosts: master_address
  become: yes
  roles:
    - City-of-Bloomington.postgresql
    - City-of-Bloomington.php

  tasks:
    - name: Install php and related packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - php-pgsql
        - postgis

    - name: Create database user
      become: yes
      become_user: postgres
      postgresql_user:
        name: "{{ ma_db.username }}"
        password: "{{ ma_db.password }}"
        state: present
        role_attr_flags: LOGIN
      no_log: True

    - name: Create database
      become: yes
      become_user: postgres
      postgresql_db: name={{ ma_db.name }} state=present

    - name: Create schema
      become: yes
      become_user: postgres
      postgresql_schema: database={{ ma_db.name }} name={{ ma_db.schema }} owner={{ ma_db.username }}

    - name: Activate PostGIS
      become: yes
      become_user: postgres
      postgresql_ext:
        name: postgis
        db: "{{ ma_db.name }}"
        state: present

    - name: Apache site configuration
      template:
        src: master_address.conf
        dest: /etc/apache2/sites-enabled/conf.d/master_address.conf
      notify: apache_restart

    - name: "Create installation directories"
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
      with_items:
        - "{{ ma_install_path }}"
        - "{{ ma_backup_path  }}"
        - "{{ ma_site_home    }}"

    - name: "Update application permissions"
      file:
        path:    "{{ item }}"
        state:   "directory"
        owner:   "www-data"
        group:   "staff"
        mode:    "g+rw"
        recurse: "yes"
      with_items:
        - "{{ ma_install_path }}"
        - "{{ ma_backup_path  }}"
        - "{{ ma_site_home    }}"
...
