---
name: 'master-address'
version:    '0.1.1'
apiVersion: 'v2'
appVersion: '2.0.7'
type:       'application'
home: 'https://github.com/City-of-Bloomington/master_address'
icon: 'https://bloomington.in.gov/static/citylogo-64.png'
...
