# Empty example values for master_address.
# This is a YAML-formatted file.
# Copy this file and declare your own variables to be passed into the templates.
---
replicaCount: 1

image:
  repository: 'docker-repo.bloomington.in.gov/cob/master_address'
  tag:        '' # Specify on the command line --set image.tag=X.x.x-abcdef00
  pullPolicy: Always
nameOverride: ""
fullnameOverride: ""


config:
  base_uri: "/master_address"
  defaults:
    city:
    state:
    locationId:

  db:
    driver: #likely pgsql
    host:
    dbname:
    schema:
    username:
    password:

  auth:
    ldap:
      classname:
      server:
      base_dn:
      username_attribute:
      user_binding:
      admin_binding:
      admin_pass:
    cas:
      server:
      uri:

  graylog:
    domain: ''
    port:


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: bloomington.in.gov
      paths: ["/master_address"]

  tls:
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
...
